trigger:
  branches:
    include:
    - 'main'
    - 'test'

  paths:
    include:
      - Posh-ACME/*
      - azure-pipelines.yml

pr: 
  - 'main'

resources:
  repositories:
    - repository: mecm-deployment
      endpoint: 'GHE-UMN'
      type: githubenterprise
      name: 'oit-hosting/mecm-deployment'

stages:
- template: azure-pipelines.yml@mecm-deployment